### ISSUE TITLE
Clicking Sign in with a passkey fails

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-webauthn#28]
Using the conditional ui it is possible to sign in. However, clicking `Sign in with a passkey` fails

**Comment by Kehrlann** [comment]
Tried on macOS, M1, Sonoma 14.5 with:

- Chrome, `126.0.6478.127`: clicking fails, does not show any UI, and logs `Uncaught (in promise) DOMException: A request is already pending.` in the console
- Safari, `17.5`: clicking fails, does not show any UI, does not log anything to the console
- Firefox Developer Edition, `128.0b9`: clicking works, shows the passkey selection UI, and login works. However, when the passkey selection UI comes up, an error is logged to the console: `Uncaught (in promise) DOMException: The operation was aborted. `

**Comment by Kehrlann** [comment]
This seems to be due to a missing `Permission-Policy`, see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/get#notallowederror) ... Unsure _why_, though.

It seems adding either `Permissions-Policy: identity-credentials-get=*` ([ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/identity-credentials-get)) or `Permissions-Policy: publickey-credentials-get=*` ([ref](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/publickey-credentials-get)) fixes the issue.

Hacked with:
```java
.headers(h -> h.addHeaderWriter((request, response) -> {
	response.setHeader("Permissions-Policy", "identity-credentials-get=*");
}))
```

**Comment by rwinch** [comment]
This has been fixed
