### ISSUE TITLE
Add tokenBindingId support

### ISSUE THREAD

**Issue by rwinch** [rwinch/spring-security-webauthn#80]

**Comment by ynojima** [comment]
Please note that Token Binding was removed from WebAuthn Level 3 due to lack of browser support.

https://www.w3.org/TR/2023/WD-webauthn-3-20230927/
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#announcement
https://groups.google.com/a/chromium.org/g/blink-dev/c/OkdLUyYmY1E/m/w2ESAeshBgAJ?pli=1

WebAuthn4J left that field just for backward compatibility.

**Comment by rwinch** [comment]
Closing as per the comment above
